remotewol/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('webapp.urls')),
    path('admin/', admin.site.urls),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, reverse, reverse_lazy

from django.contrib.auth import views as auth_views
from solo.admin import SingletonModelAdmin

from webapp import views as our_views

app_name = "webapp"

urlpatterns = [
    path('', our_views.ListDevices.as_view(), name='home'),
    path('settings/', our_views.UpdateSettings.as_view(success_url='/'), name='settings'),

    path('device/create/', our_views.CreateDevice.as_view(success_url='/'), name='create-device'),
    path('device/<int:pk>/', our_views.UpdateDevice.as_view(success_url='/'), name='update-device'),

    path('login/', auth_views.login, {'template_name': 'login_form.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),

    path('device/<int:device_id>/delete', our_views.delete_device, name='delete-device'),
    path('device/<int:device_id>/wake/', our_views.wake_device, name='wake-device'),
]

webapp/models.py
from django.db import models
from django.urls import reverse

from macaddress.fields import MACAddressField
from solo.models import SingletonModel


class Device(models.Model):
    name = models.CharField(max_length=100, default='Computer')
    mac = MACAddressField(default='00:12:3c:37:64:8f')
    secret = models.CharField(max_length=12, default='0a1b3c4d5e6f')
    description = models.TextField(default='This is a dank-ass description for a dank-af device')
    target_address = models.GenericIPAddressField(default="255.255.255.255")
    target_port = models.SmallIntegerField(default=9)
    listener = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class GeneralSettings(SingletonModel):
    listener_address = models.GenericIPAddressField(default="0.0.0.0")
    listener_port = models.SmallIntegerField(default=9)
    packet_count = models.SmallIntegerField(default=3)
    enforce_secret = models.BooleanField(default=True)

webapp/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.views.generic import View, ListView, DetailView
from solo.models import SingletonModel

from webapp.utils import wolutils

from webapp import urls
from webapp.models import Device, GeneralSettings


class ListDevices(LoginRequiredMixin, ListView):
    template_name = 'devices.html'
    model = Device

    def get_queryset(self):
        return Device.objects.all()


class CreateDevice(LoginRequiredMixin, CreateView):
    template_name = 'device_form.html'
    model = Device
    fields = ['name', 'mac', 'secret', 'description', 'target_address', 'target_port', 'listener']


class UpdateDevice(LoginRequiredMixin, UpdateView):
    template_name = 'device_form.html'
    model = Device
    fields = ['name', 'mac', 'secret', 'description', 'target_address', 'target_port', 'listener']


class UpdateSettings(LoginRequiredMixin, UpdateView):
    template_name = 'settings_form.html'
    model = GeneralSettings
    fields = ['listener_address', 'listener_port', 'packet_count']

    def get_object(self, queryset=None):
        return GeneralSettings.get_solo()


@login_required
def delete_device(request, device_id):
    device = get_object_or_404(Device, pk=device_id)
    print("Deleted device: " + str(device))
    device.delete()
    return redirect('webapp:home')


@login_required
def wake_device(request, device_id):
    device = get_object_or_404(Device, pk=device_id)
    print("Waking up device: " + str(device))
    wolutils.wake_device(device, GeneralSettings.get_solo().packet_count)

    return redirect('webapp:home')


@login_required
def temp(request):
    return HttpResponse('This is just a temporary placeholder for logged in users')

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>{% block title %}RemoteWOL{% endblock %}</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <script defer src="{% static 'js/fontawesome-all.min.js' %}"></script>

        {% block head %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'webapp:home' %}">RemoteWOL</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% block navbar_left %}
                    {% endblock %}
                </ul>

                <ul class="navbar-nav ml-auto">
                {% block navbar_right %}
                {% endblock %}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="https://github.com/Jamezrin/RemoteWOL"><i class="fab fa-github"></i></a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'webapp:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                    </li>
                {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container" style="margin-top: 80px;">
            {% block body %}
            {% endblock %}
        </div>

        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

webapp/templates/device_form.html
{% extends 'base.html' %}

{% block body %}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <div>
                <span class="text-danger small">
                    {{ field.errors }}
                </span>
            </div>
            <label>{{ field.label_tag }}</label>
            <div>{{ field }}</div>
        </div>
        {% endfor %}
        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

webapp/templates/devices.html
{% extends 'base.html' %}

{% load solo_tags %}

{% block navbar_left %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:create-device' %}"><i class="fas fa-plus"></i> Create Device</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:settings'%}"><i class="fas fa-cogs"></i> Settings</a>
    </li>
{% endblock %}

{% block body %}
    {% if object_list %}
        <ul class="list-group">
            {% for device in object_list %}
                <li class="list-group-item">
                    <a href="{% url 'webapp:update-device' device.id %}">
                        {{ device.name }}
                    </a>
                    <div class="float-right btn-group">
                        <a class="btn" href="{% url 'webapp:wake-device' device.id %}"><i class="fas fa-power-off"></i></a>
                        <a class="btn" href="{% url 'webapp:delete-device' device.id %}"><i class="fas fa-trash"></i></a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You don't have any devices, create a new one!</h3>
    {% endif %}
{% endblock %}

webapp/templates/login_form.html
{% extends 'base.html' %}

{% block title %}Login Page{% endblock %}

{% block body %}
  <h2>Login</h2>
  <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <div>
                <span class="text-danger small">
                    {{ field.errors }}
                </span>
            </div>
            <label>{{ field.label_tag }}</label>
            <div>{{ field }}</div>
        </div>
        {% endfor %}
        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

webapp/templates/settings_form.html
{% extends 'base.html' %}

{% block body %}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <div>
                <span class="text-danger small">
                    {{ field.errors }}
                </span>
            </div>
            <label>{{ field.label_tag }}</label>
            <div>{{ field }}</div>
        </div>
        {% endfor %}
        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}